# Numpy
Or called the **Numeric Python** is a library used for performing calculations on arrays and matrices. It provides faster calculation as compared to Python inbuilt libraries because the logics and algorithms in NumPy are written in C++.  

## Basics
The most basic functionality i.e. creation of array. NumPy array class `ndarray` is different from python lists and arrays. The values in the array should be of same data type. Otherwise, NumPy will implicitly typecast it to maintain homogeneity. Dimensions are called `axes`. Some of the important attributes of the class `ndarray` are `ndim`, `shape`, `size`, `dtype`, `itemsize`, and `data`. The usage of these attributes are demonstrated below.

In [1]:
import numpy as np # convention of aliasing

In [2]:
n = np.array([[1,2,3],[4,5,6]])
print(n.ndim) # dimension or number of axes
print(n.shape) # no. of rows and columns
print(n.size) # no. of element
print(n.dtype) # data type of elements
print(n.itemsize) # space occupied in bytes by each element
print(n.data) # address of buffer that stores the array
print(type(n))

2
(2, 3)
6
int64
8
<class 'numpy.ndarray'>


## Array Creation
There are many ways of creating an array. One way is using `np.array` function which takes python list as an argument. It takes a keyword argument `dtype` where the type of elements can be mentioned. Implicit typecasting is taken care by NumPy. 

In [3]:
empty_arr = np.array([])
print("empty array", empty_arr)

arr = np.array([[1,2,3],[4.0,5,6]])
print("int typecasted to float", arr, arr.dtype)

complex_arr = np.array([[1,2,3],[4.0,5,6]], dtype=complex)
print("complex array", complex_arr)

a = np.array([1,2,'one'])
print("int typecasted to str", a)
b = np.array([1,2,True,3, False,'h'])
print("bool and int typecasted to str", b)
print("--------------------------------------------------------------")

empty array []
int typecasted to float [[1. 2. 3.]
 [4. 5. 6.]] float64
complex array [[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
int typecasted to str ['1' '2' 'one']
bool and int typecasted to str ['1' '2' 'True' '3' 'False' 'h']
--------------------------------------------------------------


NumPy allows creation of placeholder matrices, provided the shape is known. This reduces the overhead of extending a 0-sized matrix. Various functions for this purpose are `ones`, `zeros`,`eye`, and `empty` among others

In [4]:
print("zeros array\n", np.zeros((2,3,4)))
print("ones array\n", np.ones((1,2,3)))
print("primary diagonal filled with one\n", np.eye(2)) # will always be a square matrix
print("empty array, filled with garbage values\n", np.empty((2,3)))
print("--------------------------------------------------------------")

zeros array
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
ones array
 [[[1. 1. 1.]
  [1. 1. 1.]]]
primary diagonal filled with one
 [[1. 0.]
 [0. 1.]]
empty array, filled with garbage values
 [[1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------------------


`arange` is analogous to `range` in python. It returns a 1D array with consecutive numbers starting from 0. `linspace(a,b,c)` returns an array of with of length c, where the elements are equidistantly placed between a and b. a and b are the first and last elements respectively in the resultant array.  

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(12,56,3)

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54])

In [7]:
"""
The parameters can be float. However, this is not advisable due to inconsistencies in storing floating point number in
Python. Hence, the length of the array generated cannot be pre-determined. 
"""
np.arange(1.2,2,0.3) 

array([1.2, 1.5, 1.8])

In [8]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
Filtering data is a one step process here.
```python
a = np.array([1,2,7,2,9,7,5,4,3,2])
b = a>3
print(b) # [False False  True False  True  True  True  True False False]
c = a[a>3]))
print(c, type(c)) # [7 9 7 5 4]  <class 'numpy.ndarray'>
```
Operations to be performed on each element of list value does not require looping.
```python
a= np.array([1,2,3,4,5])
b = a**2
print(b) # [1,2,3,16,25]
c = a+10
print(c) # [11,12,13,14,15]
```
It also supports formation of multi-dimensional arrays. Homogeneity is maintained here as well.
Accessing elements and slicing in np array is same as in python lists, i.e. through square brackets.
```
a=np.array([[1,2],[3,4],[5,6]])
print(a.shape) # (3, 2)
print(a[:,1]) # array([2, 4, 6])
print(a[1,1]) # 4
print(a[2]) # array([5, 6])
```
**.shape** return the dimensions of the array in tuple, where the first element is row and second is column.
Statistics can also be performed using np. Few functions in use are as follows:
```python
a =np.array([12, 34, 23, 92, 76, 54, 76, 83, 91])
print(np.mean(a)) # 60.111111111111114
print(np.median(a)) # 76.0
print(np.std(a)) # 28.695506595378866
b =np.array([32, 45, 63, 78, 91, 67, 87, 20, 52])
print(np.corrcoef(a)) # array([[1., 0.32346095], [0.32346095, 1.]])
```
```.mean() .median() .std() .corrcoef()``` are used to find mean, median, standard deviationand correlation coefficient respectively.