> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.


# 5 Lesser Known yet Powerful Functions in NumPy

NumPy is a library for Python which supports creation of multi-dimensional matricies along with a set of high-level mathematical functions to be performed on those matrices. It stands for **Numerical Python**. It performs complex mathematical operations must faster that Python's inbuilt libraries, because alogrithms and logics in NumPy are written in C++. Here, I shall be explaining five lesser known yet powerful functions by NumPy.

***P.S.***: In NumPy, dimensions are called axes.

- argmax
- function 2
- function 3
- function 4
- function 5

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [2]:
# List of functions explained 
function1 = np.argmax 
function2 = np.polymul
function3 = np.ndarray.flatten
function4 = np.polyder
function5 = np.char.isdigit

## Function 1 - np.argmax

`argmax` returns the index of the element with the maximum value. It assumes that the array is 1D. To get the exact index, the axis has to be defined. 

In [3]:
arr = [[7, 14], [8, 12]]

print("largest element is at index:", np.argmax(arr))
print("column-wise largest element is at indices:", np.argmax(arr, axis=0))
print("row-wise largest element is at indices:", np.argmax(arr, axis=1))

largest element is at index: 1
column-wise largest element is at indices: [1 0]
row-wise largest element is at indices: [1 1]


`arr` in 1D will look like `[7,14,8,12]`. In this the largest element is at index 1.  
`axis=0` means look for largest elements along the y for each x. `x[0] = [7,8]`. The largest element is at index 1. For `x[1] = [14,12]`, largest element is at index 1. Hence the result of `np.argmax(arr, axis=0)` is `[1,1].  


In [4]:
# argmax with 3D array
arr_3d = [[[4,3,2],[8,6,4]],[[9,5,1],[3,8,7]]]

print("largest element is at index:", np.argmax(arr_3d))
print("column-wise largest element is at indices:", np.argmax(arr_3d, axis=0))
print("row-wise largest element is at indices:", np.argmax(arr_3d, axis=1))
print("row-wise largest element is at indices:", np.argmax(arr_3d, axis=2)) 

largest element is at index: 6
column-wise largest element is at indices: [[1 1 0]
 [0 1 1]]
row-wise largest element is at indices: [[1 1 1]
 [0 1 1]]
row-wise largest element is at indices: [[0 0]
 [0 1]]


x ---------------> axis = 0 columnwise  
y z----->  
| [4,3,2]  [8,6,4]  
| [9,5,1]  [3,8,7]  
axis = 1 row-wise  
The array in 1D format will be `[4,3,2,8,6,4,9,5,1,3,8,7]`. The largest number is at index 6. The comparisons will be with vertical elements i.e. `[4,3,2]` and `[9,5,1]`, and second set as `[8,6,4]` and `[3,8,7]`

In [5]:
arr1 = [[1, 2], 
        [3, 4.]]

np.argmax(arr1, axis=3)

AxisError: axis 3 is out of bounds for array of dimension 2

If  axis value is higher than dimension, then AxisError is thrown. For easier visualization, imagine the matrix in cartesian coordinate system for dimensions <= 3. This will help to understand how argmax works.

## Function 2 - np.polymul

`polymul` returns the result after multiplication of two polynomials. The coefficients are stored as 1D matrix or an object of `poly1d`. The order of coefficients should be highest to lowest. 

In [6]:
# (2x^2 + 4x +9) * (9x+4) = 18x^3 + 44x^2 + 97x + 36
pol1 = [2,4,9]
pol2 = [9,4]
np.polymul(pol1, pol2)

array([18, 44, 97, 36])

The result is an object of `poly1d`. The highest order coefficient is the first element, and so on.

In [7]:
# (10x^3 + 8) * (6x^2 -9) = 60x^5-90x^3 +48x^2-72
pol3 = [10,0,0,8]
pol4 = [6,0,-9]
np.polymul(pol3, pol4)

array([ 60,   0, -90,  48,   0, -72])

If coefficients of certain degrees are missing, it should be filled with 0.

In [8]:
pol5 = [[1],[2],[3]]
pol6 = [4,5]
np.polymul(pol5, pol6)

ValueError: Polynomial must be 1d only.

The polynomial matrix has to be 1D, be it python list or numpy array.

## Function 3 - flatten
`flatten` is a function from `ndarray` class. It returns a copy of the array collapsed into one dimension.
 ndarray.It takes one parameter i.e. dimension. This parameter is required to decide the axis along which the flattening should take place. The acceptable values are `‘C’, ‘F’, ‘A’, ‘K’`. `C` means to flatten row-wise and `F` means to flatten in column-wise. `A` attempts flattening column-wise flattening. If fails, it switches to row-wise flattening. `K` flattens in the arr by placing the elements in the ascending order of their memory address.
The changes are not made to the original array. Hence, a modified copy of the same is returned. By default, the order is set to `C`.

In [9]:
f_arr1= np.array([[19,62],[34,56]])
f_arr1.flatten()

array([19, 62, 34, 56])

Since no order has been given, the compression happened row-wise i.e. C-style.

In [10]:
f_arr2 = np.array([[19,62],[34,90]])
f_arr2.flatten('F')

array([19, 34, 62, 90])

Order is mentioned as `F`, meaning compression should take place column-wise.

In [11]:
f_arr3 = np.array([[19,62],[34]])
f_arr3.flatten()

<ipython-input-11-55ccaa2c0c2b>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  f_arr3 = np.array([[19,62],[34]])


array([list([19, 62]), list([34])], dtype=object)

`flatten` works as desired when the size of the matrix has 4 edges only. If there is inconsistency in the size of row and columns, the function just typecasts the arrays to lists and returns.

## Function 4 - np.polyder

`np.polyder` can be used to find the derivative of a polynomial. It accepts an object of `poly1d` or a sequence as it parameter. It accepts one more optional parameter `m` i.e. order of differentiation. By default, it is one. This function returns an object of `poly1d`.

In [12]:
d1 = np.array([5,6,7,8])
print(np.polyder(d1))
d2 = np.array([5,6,7,8,0])
print(np.polyder(d2))

[15 12  7]
[20 18 14  8]


The size of the resultant polynomial will be atleast one less than the size of original matrix

In [13]:
d3 = np.array([9,12,8,3])
print(np.polyder(d3, m=3))
print(np.polyder(d3, m=5))

[54]
[]


If value of m is larger than the size of original array, the result will always be an empty object.

In [14]:
d4 = [[9,12],[8,3]]
np.polyder(d4)

ValueError: operands could not be broadcast together with shapes (0,2) (0,) 

Polynomial vector must be 1D for the desired output. 

## Function 5 - np.char.isdigit

`np.char.isidigit` returns a matrix with boolean values where elements are populated by checking the value type of corresponding elements in the target martix. 

In [15]:
c1 = np.array([["hello","p"],["2","there"]])
np.char.isdigit(c1)

array([[False, False],
       [ True, False]])

All elements that are type int or a string with int value will return True 

In [16]:
c2 = np.array([[True,"pass"],["2.3","9"]])
np.char.isdigit(c2)

array([[False, False],
       [False,  True]])

Implicit typecasting of bool or float does not take place. Therefore, the return False.

In [17]:
c3 = np.array([["true","pass"],[1,"9"]])
np.char.isdigit(c3)

array([[False, False],
       [ True,  True]])

This function is useful to decide the next set of operations which might depend on the data type of elements

## Conclusion

NumPy is one of the most well-documented libraries in Python. It has a huge community that works on improving it every day. This library is completely open source. https://github.com/numpy/numpy Feel free to reach out to the community. You are more than welcome to contribute to the code. 

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* https://numpy.org/devdocs/reference/index.html